[default.files]
foot = "~/.config/foot"
fish = "~/.config/fish"
gnupg = "~/.config/gnupg"
ssh = "~/.ssh"
git = "~/.config/git"
nvim = "~/.config/nvim"
paru = "~/.config/paru"
fuzzel = "~/.config/fuzzel"
